version: "3.9"
services:
  php:
    build:
      context: ./.build/${PHP_VERSION}
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      XDEBUG_CONFIG: "client_host=192.168.222.1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - "./:/var/www/html"
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.222.0/28